# Generated by Django 3.2.9 on 2022-05-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0003_auto_20211226_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('admin', 'Admin')], max_length=55, null=True),
        ),
    ]
